CREATE_USER_TABLE_QUERY = """
         CREATE TABLE IF NOT EXISTS bot_users
         (
         ID INTEGER PRIMARY KEY,
         TELEGRAM_ID INTEGER,
         USERNAME VARCHAR(50),
         FIRST_NAME VARCHAR(50),
         LAST_NAME VARCHAR(50),
         UNIQUE (TELEGRAM_ID)
         )

"""
ALTER_USER_TABLE = """
ALTER TABLE bot_users
ADD COLUMN REFERENCE_LINK TEXT
"""
CREATE_BAN_USER_TABLE_QUERY = '''
    CREATE TABLE IF NOT EXISTS ban_users
    (
    ID INTEGER PRIMARY KEY,
    TELEGRAM_ID INTEGER,
    USERNAME CHAR(50),
    COUNT INTEGER,
    UNIQUE (TELEGRAM_ID)
    )
'''
CREATE_USER_FORM_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS user_form 
        (
        ID INTEGER PRIMARY KEY,
        TELEGRAM_ID INTEGER,
        NICKNAME CHAR(50),
        BIO TEXT,
        AGE INTEGER,
        OCCUPATION CHAR(50),
        PHOTO TEXT,
        UNIQUE (TELEGRAM_ID)
        )
"""
CREATE_LIKE_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS like_user 
        (
        ID INTEGER PRIMARY KEY,
        OWNER_TELEGRAM_ID INTEGER,
        LIKER_TELEGRAM_ID INTEGER,
        UNIQUE (OWNER_TELEGRAM_ID, LIKER_TELEGRAM_ID)
        )
"""
CREATE_DISLIKE_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS dislike_user 
        (
        ID INTEGER PRIMARY KEY,
        OWNER_TELEGRAM_ID INTEGER,
        DISLIKER_TELEGRAM_ID INTEGER,
        UNIQUE (OWNER_TELEGRAM_ID, DISLIKER_TELEGRAM_ID)
        )
"""
CREATE_REFERENCE_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS referral 
        (
        ID INTEGER PRIMARY KEY,
        OWNER_TELEGRAM_ID INTEGER,
        REFERRAL_TELEGRAM_ID INTEGER,
        UNIQUE (OWNER_TELEGRAM_ID, REFERRAL_TELEGRAM_ID)
        )
"""

INSERT_USER_QUERY = """
INSERT OR IGNORE INTO bot_users VALUES (?,?,?,?,?,?)"""

INSERT_BAN_USER_QUERY = '''
INSERT OR IGNORE INTO ban_users VALUES (?,?,?,?)'''

INSERT_USER_FORM_QUERY = """
INSERT INTO user_form VALUES (?,?,?,?,?,?,?)
"""
INSERT_LIKE_QUERY = """
INSERT INTO like_user VALUES (?,?,?)
"""

INSERT_DISLIKE_QUERY = """
INSERT INTO dislike_user VALUES (?,?,?)
"""
INSERT_REFERRAL_QUERY = """
INSERT INTO referral VALUES (?,?,?)
"""

SELECT_BAN_USER = """
SELECT * FROM ban_users WHERE TELEGRAM_ID = ?"""

SELECT_ALL_USER_QUERY = '''
SELECT * FROM bot_users'''

SELECT_USER_QUERY = '''
SELECT * FROM bot_users WHERE TELEGRAM_ID = ?'''

SELECT_USER_FORM_QUERY = """
SELECT * FROM user_form WHERE TELEGRAM_ID = ?
"""
SELECT_ALL_USERS_FORM_QUERY = """
SELECT * FROM user_form
"""

UPDATE_BAN_USER_COUNT_QUERY = '''
UPDATE ban_users SET COUNT = COUNT + 1 WHERE TELEGRAM_ID  = ?'''
UPDATE_USER_FORM_QUERY = """
UPDATE user_form SET NICKNAME = ?, BIO = ?, AGE = ?, OCCUPATION = ?, PHOTO = ? WHERE TELEGRAM_ID = ?
"""
UPDATE_USER_REFERENCE_LINK_QUERY = """
UPDATE bot_users SET REFERENCE_LINK = ? WHERE TELEGRAM_ID = ?
"""

DELETE_USER_FORM_QUERY = """
DELETE FROM user_form WHERE TELEGRAM_ID = ?
"""
SELECT_LIKER_USER = """
SELECT OWNER_TELEGRAM_ID FROM like_user WHERE LIKER_TELEGRAM_ID = ?
"""
SELECT_DISLIKER_USER = """
SELECT OWNER_TELEGRAM_ID FROM dislike_user WHERE DISLIKER_TELEGRAM_ID = ?
"""
SELECT_USER_BY_LINK_QUERY = """
SELECT * FROM bot_users WHERE REFERENCE_LINK = ?
"""
SELECT_ALL_REFERRAL_BY_OWNER_QUERY = """
SELECT * FROM referral WHERE OWNER_TELEGRAM_ID = ?
"""
